version: '2'
services:
    jhipstercassandrasampleapplication-cassandra:
        image: cassandra:3.9
        # volumes:
        #     - ~/volumes/jhipster/jhipsterCassandraSampleApplication/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
        environment:
            - MAX_HEAP_SIZE=256M
            - HEAP_NEWSIZE=128M
    jhipstercassandrasampleapplication-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: jhipstercassandrasampleapplication-cassandra-migration
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace.cql
            - MAX_HEAP_SIZE=256M
            - HEAP_NEWSIZE=128M
